const dummyData = [
  {
    first_name: 'John',
    last_name: 'Doe',
    username: 'DoeJ',
    password: '$2b$10$EjWAPqe40rgd5yv8Xruoiem9vnn.FnhDkAjLiFbh7J.91uzwdahqm',
    total_mins: 50000,
    visit_count: 3,
    current_river: null,
    current_activity: null,
    location: 'New York',
    travel_History: ['Bail', 'Germany'],
    certification: 'Yoga Master',
  },
  {
    first_name: 'Jane',
    last_name: 'Smith',
    username: 'JaneSmith',
    password: '$2b$10$EjWAPqe40rgd5yv8Xruoiem9vnn.FnhDkAjLiFbh7J.91uzwdahqm',
    total_mins: 5,
    visit_count: 1,
    current_river: null,
    current_activity: null,
    location: 'Spain',
    travel_History: ['Canada', 'Mexico'],
    certification: 'None',
  },
  {
    first_name: 'Larry',
    last_name: 'Lambert',
    username: 'LarryL',
    password: '$2b$10$EjWAPqe40rgd5yv8Xruoiem9vnn.FnhDkAjLiFbh7J.91uzwdahqm',
    total_mins: 500,
    visit_count: 10,
    current_river: null,
    current_activity: null,
    location: 'New Jersey',
    travel_History: [],
    certification: 'Some',
  },
  {
    first_name: 'Stephen',
    last_name: 'Mark',
    username: 'MarkS',
    password: '$2b$10$EjWAPqe40rgd5yv8Xruoiem9vnn.FnhDkAjLiFbh7J.91uzwdahqm',
    total_mins: 100,
    visit_count: 4,
    current_river: null,
    current_activity: null,
    location: 'Bali',
    travel_History: ['Rivers', 'Mountains', 'etc'],
    certification: 'Namaslaying',
  },
];

module.exports = dummyData;
